name: Django Migration Inspection
description: 'Migration Inspector for Django projects'
inputs:
  database:
    description: 'database alias'
    required: false
    default: 'default'
    type: string
  skip-history-check:
    description: 'skip history check'
    required: false
    default: false
    type: boolean
  root-dir:
    description: 'root directory for django app'
    required: true
    default: '.'
    type: string
runs:
  using: "composite"
  steps:
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -i https://test.pypi.org/simple/ django-migration-inspector==0.0.5
    shell: bash
  - name: Django Migrations Inspection
    run: |
      cd ${{ inputs.root-dir }}
      command="manage.py inspectmigrations"
      if [[ "${{ inputs.database }}" != "default" ]]; then
        command+=" --database=${{ inputs.database }}"
      fi
      if [[ ${{ inputs.skip-history-check }} == true ]]; then
        command+=" --skip-history-check"
      fi
      ./$command
    shell: bash