name: Django Migration Inspection
description: 'Github action to automate Django Migration Inspection'
inputs:
  database:
    description: 'database alias'
    required: false
    default: 'default'
    type: string
  skip-history-check:
    description: 'skip history check'
    required: false
    default: false
    type: boolean
  root-dir:
    description: 'root directory for django app'
    required: true
    default: '.'
    type: string
runs:
  using: "composite"
  steps:
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install django-migration-inspector
    shell: bash
  - name: Django Migrations Inspection
    id: django-migration-inspector
    run: |
      cd ${{ inputs.root-dir }}
      command="manage.py inspectmigrations"
      if [[ "${{ inputs.database }}" != "default" ]]; then
        command+=" --database=${{ inputs.database }}"
      fi
      if [[ ${{ inputs.skip-history-check }} == true ]]; then
        command+=" --skip-history-check"
      fi
      ./$command
    shell: bash
  - name: Alert Failure on Slack
    if: ${{ failure() && steps.django-migration-inspector.conclusion == 'failure'}}
    shell: bash
    run: |
      echo "Django Migration Inspection Failed"
      echo "slack url ${{ env.SLACK_WEBHOOK_URL }} ${{WORKFLOW_URL}} ${{WORKFLOW_NUMBER}}"
      