# Generated by Django 3.2 on 2024-01-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
