# Generated by Django 3.2 on 2023-10-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0003_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='MyModel',
            name='test_field2',
            field=models.BooleanField(default=False, null=True, blank=True),
        ),
    ]
