name: Manually deploy to QA
on:
  pull_request:
    branches: [ develop, master ]

jobs:
  deployqa:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: beacondb
          POSTGRES_USER: pgbounceruser
          POSTGRES_PASSWORD: pgbouncerpass
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare URLDB
        run: |
          export PGPASSWORD=pgbouncerpass
          createdb -h localhost -p 5432 -U pgbounceruser urldb
      - name: Check Migrations
        id: django-migration-inspector
        uses: ./.github/actions/django-migration-inspector
        with:
          skip-history-check: true
          root-dir: './django_POC'
          restore-key: ${{ runner.os }}-pip-${{ hashFiles('./django_POC/*requirements.pip') }}
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_URL: https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}
          WORKFLOW_NUMBER: ${{ github.run_number }}
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
          ACTOR: ${{ github.actor }}