name: Manually deploy to QA
on:
  workflow_dispatch:

jobs:
  deployqa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: List Directory
        run: ls -a
      - name: Check Migrations
        id: django-migration-inspector
        uses: ./.github/actions/django-migration-inspector
        with:
          skip-history-check: true
          root-dir: 'django_POC/'
        env:
          WORKFLOW_URL: https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}
          WORKFLOW_NUMBER: ${{ github.run_number }}
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
          ACTOR: ${{ github.actor }}
          ACTOR_AVATAR: ${{ github.event.actor.avatar_url }}
      - name: Deploy to QA
        run: |
          echo "Deploying to QA"
          echo "Deployed to QA"
      - name: Building Docker Image
        run: |
          echo "Building Docker Image"
      - name: Another Step
        run: |
          echo "Deploying to QA"
          echo "Deployed to QA"
      - name: Another Step
        run: |
          echo "Building Docker Image"
