name: Manually deploy to QA
on:
  workflow_dispatch:
  push:

jobs:
  deployqa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: List Directory
        run: ls -a

      - name: Cache Python dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./django_POC/*requirements.txt') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Cache Hit missed"
          apt-get update
          apt-get install -y gcc
          pip install -r django_POC/requirements.txt
          pip install -r django_POC/test-requirements.txt

      - name: Check Migrations
        id: django-migration-inspector
        uses: ./.github/actions/django-migration-inspector
        with:
          skip-history-check: true
          root-dir: 'django_POC/'
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_URL: https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}
          WORKFLOW_NUMBER: ${{ github.run_number }}
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
          ACTOR: ${{ github.actor }}
      - name: Deploy to QA
        run: |
          echo "Deploying to QA"
          echo "Deployed to QA"
      - name: Building Docker Image
        run: |
          echo "Building Docker Image"
      - name: Another Step
        run: |
          echo "Deploying to QA"
          echo "Deployed to QA"
      - name: Another Step
        run: |
          echo "Building Docker Image"
