name: Manually deploy to QA
on:
  workflow_dispatch:

jobs:
  deployqa:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: List Directory
        run: ls -a
      - name: Check Migrations
        id: django-migration-inspector
        uses: ./.github/actions/django-migration-inspector
        with:
          skip-history-check: true
          root-dir: 'django_POC/'
      - name: Post Failure to the Slack Channel
        if: ${{ failure() && steps.django-migration-inspector.conclusion == 'failure'}}
        env:
          WORKFLOW_URL: https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}
          WORKFLOW_NUMBER: ${{ github.run_number }}
          SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
        run: |
          curl --location $SLACK_WEBHOOK_URL \
          --header 'Content-Type: application/json' \
          --data '{
              "blocks": [
                  {
                      "type": "header",
                      "text": {
                          "type": "plain_text",
                          "text": "Migration error on ${{ github.workflow }}",
                          "emoji": true
                      }
                  },
                  {
                      "type": "divider"
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "👮🏼‍♀️ Inspector exited with code 1 due to inconsistencies in migration files. For additional information you can head out to the Github workflow using the button below."
                      },
                      "accessory": {
                          "type": "image",
                          "image_url": "https://pbs.twimg.com/profile_images/625633822235693056/lNGUneLX_400x400.jpg",
                          "alt_text": "cute cat"
                      }
                  },
                  {
                      "type": "divider"
                  },
                  {
                      "type": "section",
                      "text": {
                          "type": "mrkdwn",
                          "text": "Visit the Github workflow."
                      },
                      "accessory": {
                          "type": "button",
                          "text": {
                              "type": "plain_text",
                                "text": "#${{ env.WORKFLOW_NUMBER }}",
                              "emoji": true
                          },
                          "value": "click_me_123",
                          "url": "${{ env.WORKFLOW_URL }}",
                          "action_id": "button-action"
                      }
                  }
              ]
          }'


